---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-service-config
  namespace: keptn
data:
  # general configuration for mongodb-service
  DUMP_DIR: "/data/dumpdir"
  # configuration for carts service
  CARTS_SOURCEDB: "carts-db"
  CARTS_TARGETDB: "carts-db-canary"
  CARTS_PORT: "27017"
  CARTS_SOURCE_HOST: "carts-db"
  CARTS_TARGET_HOST: "carts-db-canary"
  CARTS_COLLECTIONS: "" 
